[workspace]
members = [
	"primitives/avail",
	"kate",
]
[patch.crates-io]
# Substrate  (polkadot-v0.9.13).
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13" }

# Frame
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.13" }

