[workspace]
resolver = "2"
members = [
	"core",
	"kate/recovery",
	"kate",
	"nomad/signature",
	"nomad/core",
	"nomad/base",
	"nomad/merkle",
]
[patch.crates-io]
# Substrate  (polkadot-v1.0.0).
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-core-hashing = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }

[profile.dev.package]
nalgebra = { opt-level = 3 }
blst = { opt-level = 3 }
dusk-bls12_381 = { opt-level = 3 }
dusk-plonk = { opt-level = 3 }
dusk-jubjub = { opt-level = 3 }
dusk-bytes = { opt-level = 3 }
rayon = { opt-level = 3 }
rayon-core = { opt-level = 3 }
poly-multiproof = { opt-level = 3 }
ark-bls12-381 = { opt-level = 3 }
ark-ec = { opt-level = 3 }
ark-ff = { opt-level = 3 }
ark-poly = { opt-level = 3 }
ark-serialize = { opt-level = 3 }
ark-std = { opt-level = 3 }
merlin = { opt-level = 3 }
