[package]
name = "da-primitives"
version = "0.4.6"
authors = []
edition = "2021"

[dependencies]
# Internal
da-types = { path = "../types", default-features = false }

# Others
hash256-std-hasher = { version = "0.15.2", default-features = false }
log = { version = "0.4.8", default-features = false }
serde = { version = "1", optional = true, features = ["derive"] }
thiserror-no-std = "2.0.2"

# Substrate
beefy-merkle-tree = { git = "https://github.com/paritytech/substrate.git/", branch = "polkadot-v0.9.37", default-features = false }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "max-encoded-len"] }
frame-support = { version = "4.0.0-dev", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-core = { version = "7", default-features = false }
sp-runtime = { version = "7", default-features = false }
sp-runtime-interface = { version = "7", default-features = false }
sp-std = { version = "5", default-features = false }
sp-trie = { version = "7.0.0", default-features = false }

[dev-dependencies]
hex-literal = "0.3.4"
serde_json = "1"
test-case = "1.2.3"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"log/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-trie/std",
	"sp-runtime-interface/std",
	"hash256-std-hasher/std",
	"frame-support/std",
	"beefy-merkle-tree/std",
	"da-types/std",
]

header-backward-compatibility-test = []
try-runtime = [
	"sp-runtime/try-runtime",
]
