[package]
name = "kate-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.41"
dusk-bytes = "0.1.6"
dusk-plonk = { git = "https://github.com/maticnetwork/plonk.git", tag = "v0.12.0-polygon-1" }
merlin = "3.0"
rand = "0.8.4"
rand_chacha = "0.3"
