[package]
name = "da-types"
version = "0.4.4"
authors = []
edition = "2018"

[dependencies]
# Substrate
parity-scale-codec = { version = "3", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
sp-core = { version = "7", default-features = false }

# 3rd-parties
derive_more = "0.99.17"
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
	"serde", 
	"sp-core/std",
	"parity-scale-codec/std", 
	"scale-info/std", 
	"num-traits/std"
]
