[package]
name = "kate-recovery"
version = "0.8.1"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2018"

[dependencies]
# Internals
dusk-plonk = { git = "https://github.com/availproject/plonk.git", tag = "v0.12.0-polygon-2" }

# Substrate
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
sp-arithmetic = { version = "6", default-features = false }

# 3rd-parties
dusk-bytes = { version = "0.1.6", default-features = false }
once_cell = { version = "1.9.0", optional = true }
rand = { version = "0.8.4", optional = true }
rand_chacha = { version = "0.3", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
static_assertions = "1.1.0"
thiserror-no-std = "2.0.2"

[dev-dependencies]
hex = "0.4"
test-case = "1.2.3"

[features]
default = ["std"]
std = [
	"once_cell",
	"rand",
	"rand_chacha",
	"serde",
	"sp-arithmetic/std",
]
