[package]
name = "kate"
version = "0.7.0"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
dusk-bytes = { version = "0.1.6", default-features = false, optional = true }
dusk-plonk = { git = "https://github.com/maticnetwork/plonk", branch = "will/polynomial-visibility", optional = true }
hex = { version = "0.4", default-features = false, features = ["alloc"], optional = true }
kate-recovery = { path = "recovery", default-features = false, optional = true }
log = { version = "0.4.8", optional = true }
once_cell = { version = "1.8.0", optional = true }
rand = { version = "0.8.4", default-features = false, optional = true }
rand_chacha = { version = "0.3", default-features = false, optional = true }
rayon = { version = "1.5.2", optional = true }
serde = { version = "1.0.121", optional = true, features = ["derive"] }
sp-arithmetic = { version = "7.0.0", default-features = false }
sp-std = { version = "4.0.0", default-features = false }
sp-core-hashing = { version = "5.0.0", default-features = false, optional = true }
static_assertions = "1.1.0"
kate-grid = { path = "grid" }
da-types = { path = "../primitives/types" }
poly-multiproof = { git = "https://github.com/aphoh/poly-multiproof", default-features = false, rev = "3345c76b84a14accb90020974a8cab837fe598a0" }

[dev-dependencies]
criterion = "0.3.5"
hex-literal = "0.3.4"
itertools = "0.10"
proptest = "1.0.0"
serde_json = "1.0"
test-case = "1.2.3"

[features]
default = ["std"]
alloc = ["dusk-plonk/alloc"]

std = [
	"kate-recovery/std",
  "hex",
	"hex/std",
	"once_cell",
	"codec/std",
	"alloc",
	"serde",
	"rayon",
	"rand",
	"rand_chacha/std",
	"log",
	"dusk-plonk/std",
	"dusk-bytes",
	"sp-std/std",
	"da-types/std",
  "sp-arithmetic/std",
  "sp-core-hashing",
  "sp-core-hashing/std",
  "poly-multiproof/blst",
]
substrate = [
  "da-types/substrate",
]
extended-columns = []
maximum-block-size = []

[[bench]]
name = "kzg"
harness = false
