[package]
name = "kate"
version = "0.7.1"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Pending to review
poly-multiproof = { git = "https://github.com/aphoh/poly-multiproof", default-features = false, rev = "1ec7c7eca0861ad89427c45534006f49d039820a" }

# Internal
da-types = { path = "../primitives/types", default-features = false }
dusk-plonk = { git = "https://github.com/availproject/plonk.git", tag = "v0.12.0-polygon-2", optional = true }
kate-recovery = { path = "recovery", default-features = false, optional = true }
# kate-grid = { path = "grid" }

# Parity & Substrate
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
sp-arithmetic = { version = "6", default-features = false }
sp-core = { version = "7.0.0", default-features = false, optional = true }

# 3rd-party
derive_more = { version = "0.99.17", default-features = false, features = ["constructor"] }
dusk-bytes = { version = "0.1.6", default-features = false }
hex = { version = "0.4", optional = true, default-features = false, features = ["alloc"] }
hex-literal = { version = "0.3.4", optional = true }
log = { version = "0.4.8", optional = true }
nalgebra = { version = "0.32.2", default-features = false }
once_cell = { version = "1.8.0", optional = true }
rand = { version = "0.8.4", default-features = false, optional = true }
rand_chacha = { version = "0.3", default-features = false, optional = true }
rayon = { version = "1.5.2", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
static_assertions = "1.1.0"
thiserror-no-std = "2.0.2"

[dev-dependencies]
proptest = "1"
serde_json = "1"
test-case = "1.2.3"

[features]
default = ["std"]
alloc = ["dusk-plonk/alloc", "nalgebra/alloc"]
parallel = ["rayon"]

std = [
	"kate-recovery/std",
	"once_cell",
	"hex-literal",
	"hex",
	"codec/std",
	"serde",
	"rand",
	"rand_chacha/std",
	"log",
	"dusk-plonk/std",
	"da-types/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"poly-multiproof/blst",
	"nalgebra/std",
]

extended-columns = []
maximum-block-size = []

[[bench]]
name = "kzg"
harness = false
