[package]
name = "kate"
version = "0.7.1"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
da-types = { path = "../primitives/types", default-features = false }
dusk-bytes = { version = "0.1.6", default-features = false, optional = true }
dusk-plonk = { git = "https://github.com/availproject/plonk.git", tag = "v0.12.0-polygon-2", optional = true }
frame-support = { version = "4.0.0-dev", default-features = false }
getrandom = { version = "0.2", features = ["js"], optional = true }
hex = { version = "0.4", default-features = false, features = ["alloc"] }
hex-literal = "0.3.4"
kate-grid = { path = "grid" }
kate-recovery = { path = "recovery", default-features = false, optional = true }
log = { version = "0.4.8", optional = true }
once_cell = { version = "1.8.0", optional = true }
poly-multiproof = { git = "https://github.com/aphoh/poly-multiproof", default-features = false, rev = "1ec7c7eca0861ad89427c45534006f49d039820a" }
rand = { version = "0.8.4", default-features = false, optional = true }
rand_chacha = { version = "0.3", default-features = false, optional = true }
rayon = { version = "1.5.2", optional = true }
serde = { version = "1.0.121", optional = true, features = ["derive"] }
sp-arithmetic = { version = "7.0.0", default-features = false }
sp-core-hashing = { version = "5.0.0", default-features = false, optional = true }
sp-std = { version = "4.0.0", default-features = false }
static_assertions = "1.1.0"

[dev-dependencies]
criterion = "0.3.5"
itertools = "0.10"
proptest = "1.0.0"
serde_json = "1.0"
test-case = "1.2.3"

[features]
default = ["std"]
alloc = ["dusk-plonk/alloc"]
parallel = ["std", "rayon", "kate-grid/parallel"]

std = [
	"kate-recovery/std",
	"hex/std",
	"once_cell",
	"codec/std",
	"alloc",
	"serde",
	"rayon",
	"rand",
	"rand_chacha/std",
	"log",
	"dusk-plonk/std",
	"dusk-bytes",
	"sp-std/std",
	"da-types/std",
	"sp-arithmetic/std",
	"sp-core-hashing",
	"sp-core-hashing/std",
	"poly-multiproof/blst",
]
substrate = [
	"da-types/substrate",
]
extended-columns = []
maximum-block-size = []

[[bench]]
name = "kzg"
harness = false
