name: Polygon Avail CI
on:
  push:
    branches:
      - main
      - develop
      - will/grid-refactor
  pull_request:
    branches:
      - main
      - develop
      - will/grid-refactor

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        # A repository can have up to 10GB of caches.
        # Check https://github.com/actions/cache for details.
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain 1.64 
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.64
            components: clippy, llvm-tools-preview
            default: true
            profile: minimal

      - name: Check `TOML`, `JSON`, and `MarkDown` formatting
        uses: dprint/check@v2.1

      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Check Clippy 
        uses: actions-rs/cargo@v1
        with:
          command: clippy 
          args: --check

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --features "avail-core/runtime"
        env:
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "profile-%p-%m.profraw"

      - name: Generate test code coverage report
        run: |
          cargo +stable install --force grcov
          grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o lcov.info

      - name: Upload test code coverage report to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info

      - name: Cleanup
        run: find . -name \*.profraw -type f -exec rm -f {} +

      # Run Bencmarks 
      - name: Run benchmark
        run: cargo bench --features "avail-core/runtime" | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: output.txt
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          # Mention users in the commit comment
          # alert-comment-cc-users: '@fmiguelgarcia,@delroybosco,@prabal-banerjee,@kroos47,@jakubcech'

